### ISSUE TITLE
cert based authentication

### ISSUE THREAD

**Issue by ddastoli** [ciscoecosystem/terraformer#36]
Currently terraform only supports username and password. cert based authentication should be supported as well.

**Comment by RutvikS-crest** [comment]
Hi @ddastoli,
We have implemented certificate-based authentication to the terraformer.
```bash
terraformer import aci --resources=tenant --base-url=Cisco_APIC_url --username=Cisco_APIC_username --private-key="private.key" --cert-name="user_cert"
```
make sure `ACI_PASSWORD` environment variable is not set, certificate-based auth will only work if `ACI_PASSWORD` is empty.
